# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LoginHistory.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'LoginHistory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12LoginHistory.proto\"2\n\x0cLoginHistory\x12\"\n\rlogin_entries\x18\x01 \x03(\x0b\x32\x0b.LoginEntry\"~\n\nLoginEntry\x12\x11\n\tLastLogin\x18\x01 \x01(\x03\x12\r\n\x05\x45xtra\x18\x02 \x01(\x05\x12\x13\n\x0b\x44\x65viceModel\x18\x03 \x01(\t\x12\x1a\n\x12\x44\x65viceArchitecture\x18\x04 \x01(\t\x12\x1d\n\tLoginType\x18\x05 \x01(\x0e\x32\n.LoginType*_\n\tLoginType\x12\x16\n\x12UNKNOWN_LOGIN_TYPE\x10\x00\x12\t\n\x05USUAL\x10\x01\x12\x0f\n\x0bUSUAL_LOGIN\x10\x02\x12\x0b\n\x07UNUSUAL\x10\x03\x12\x11\n\rUNUSUAL_LOGIN\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LoginHistory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINTYPE']._serialized_start=202
  _globals['_LOGINTYPE']._serialized_end=297
  _globals['_LOGINHISTORY']._serialized_start=22
  _globals['_LOGINHISTORY']._serialized_end=72
  _globals['_LOGINENTRY']._serialized_start=74
  _globals['_LOGINENTRY']._serialized_end=200
# @@protoc_insertion_point(module_scope)
